name: build
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: ['zulu', 'temurin']
        java: ['8', '11', '17']
    name: Java ${{ matrix.java }} (${{ matrix.distribution }})
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - name: Build and test
        env:
          USER_ID: ${{ secrets.USER_ID }}
          ENTERPRISE_ID: ${{ secrets.ENTERPRISE_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          JWT_CONFIG_BASE_64: ${{ secrets.JWT_CONFIG_BASE_64 }}
          BOX_EXTERNAL_USER_EMAIL: ${{ secrets.BOX_EXTERNAL_USER_EMAIL }}
        run: ./gradlew check --stacktrace
